<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Shopping List</title>
    <link href="//fonts.googleapis.com/css?family=Lato:300" rel="stylesheet" type="text/css">
    <link href="./css/style.css" rel="stylesheet" type="text/css">
    <script defer src="/js/script.js"></script>
</head>
<body>
<main>
    <header>
        <h1>Mayden Shopping List</h1>
    </header>
    <div class="addItemFormContainer">
        <form id="addItem" method="post" action="/item">
            <input id="userInput" name="item" type="text" placeholder="add new item" maxlength="50" minlength="1">
            <input type="submit" value="Add item">
            <input type="hidden" name="item" value="1">
        </form>
        <p id="errorMessage" <?php echo ' class="visible">' . $errorMsg; ?></p>
    </div>
    <section id="shoppingList">
        <ul id="listItems">
            <?php echo \ShoppingList\ViewHelpers\ShoppingListView::shoppingListView($shoppingListItems); ?>
        </ul>
    </section>
</main>
</body>
</html>
