<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Shopping List</title>
    <link href="//fonts.googleapis.com/css?family=Lato:300" rel="stylesheet" type="text/css">
    <link href="../public/css/style.css" rel="stylesheet" type="text/css">
</head>
<body>
<main>
    <header>
        <h1>Mayden Shopping List</h1>
    </header>
    <section id="shoppingList">
        <ul id="listItems">
            <?php echo \ShoppingList\ViewHelpers\ShoppingListView::shoppingListView($shoppingListItems); ?>
        </ul>
    </section>
</main>
</body>
</html>
